#!/usr/bin/php
<?php
if ($argc!==4) {
    print ("Неверное количество аргументов");
    exit(200);
}

class URFA {
		private $link;
		private $result;
		private $token;
        private $login;
        private $pass;
        private $new_pass;
		function con($token){
			$link = mysql_connect('127.0.0.1','root','') or die('Не удалось соединиться: ' . mysql_error());
			mysql_select_db('UTM5') or die('Не удалось выбрать базу данных');
			$result = mysql_query("call proc_get_account_info('".$token."',@r1,@r2,@r3,@r4,@r5,@r6,@r7,@r8,@r9);") or die('Запрос не удался: ' . mysql_error());
			$result2=mysql_query("SELECT @r2");
			$login = mysql_fetch_row($result2)[0];
			return $login;
		}
        function cp($login,$pass,$new_pass) {
                //$login=$argv[1];
                //$pass=$argv[2];
                //$new_pass=$argv[3];
                if (!shell_exec("urfa -u -l '".$login."' -P '".$pass."' -a user5_change_password -old_password '".$pass."' -new_password '".$new_pass."' -new_password_ret '". $new_pass."' 2>/dev/null")) {
                        error_log("Неверный логин или пароль!");
                        exit(1);
                }
                else {
                        error_log("Успешно выполнено!");
                        exit(0);
                }
        }
}

$obj=new URFA();
$x = $obj->cp($obj->con($argv[1]),$argv[2],$argv[3]);
echo "$x";
//$obj->cp($argv[1],$argv[2],$argv[3]);
?>

